############# Magyar navigáció ##############

# főmenü
[[main]]
name = "Országok"
weight = 1

[[main]]
parent = "Országok"
name = "Magyarország"
pageRef = "/guides/hungary"
weight = 1

[[main]]
name = "Összes Útmutató"
pageRef = "/guides"
weight = 2

# lábléc menü
[[footer]]
name = "Közreműködők"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Feltételek"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Adatvédelmi Szabályzat"
pageRef = "/privacy-policy"
weight = 3
