############# Navegação em português ##############

# menu principal
[[main]]
name = "Países"
weight = 1

[[main]]
parent = "Países"
name = "Portugal"
pageRef = "/categories/portugal"
weight = 1

[[main]]
name = "Todos os Guias"
pageRef = "/guides"
weight = 2

# menu de rodapé
[[footer]]
name = "Colaboradores"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Termos"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Política de Privacidade"
pageRef = "/privacy-policy"
weight = 3
