############# English navigation ##############

# main menu
[[main]]
name = "Countries"
weight = 1

[[main]]
parent = "Countries"
name = "Spain"
pageRef = "/categories/spain"
weight = 1

[[main]]
parent = "Countries"
name = "Germany"
pageRef = "/categories/germany"


[[main]]
parent = "Countries"
name = "Italy"
pageRef = "/categories/italy"


[[main]]
parent = "Countries"
name = "Switzerland"
pageRef = "/categories/switzerland"

[[main]]
name = "All Guides"
pageRef = "/guides"
weight = 2

# footer menu
[[footer]]
name = "Contributors"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Terms"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3