############# Navegación en español ##############

# menú principal
[[main]]
name = "Países"
weight = 1

[[main]]
parent = "Países"
name = "España"
pageRef = "/guides/spain"
weight = 11

[[main]]
name = "Todas las Guías"
pageRef = "/guides"
weight = 2

# menú de pie de página
[[footer]]
name = "Colaboradores"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Términos"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Política de Privacidad"
pageRef = "/privacy-policy"
weight = 3