############# Българска навигация ##############

# главно меню
[[main]]
name = "Държави"
weight = 1

[[main]]
parent = "Държави"
name = "България"
pageRef = "/categories/bulgaria"
weight = 1

[[main]]
name = "Всички Ръководства"
pageRef = "/guides"
weight = 2

# меню за долен колонтитул
[[footer]]
name = "Сътрудници"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Условия"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Политика за Поверителност"
pageRef = "/privacy-policy"
weight = 3
