############# Hrvatska navigacija ##############

# glavni izbornik
[[main]]
name = "Zemlje"
weight = 1

[[main]]
parent = "Zemlje"
name = "Austrija"
pageRef = "/categories/austria"
weight = 1

[[main]]
parent = "Zemlje"
name = "Hrvatska"
pageRef = "/categories/croatia"
weight = 1

[[main]]
name = "Svi Vodiči"
pageRef = "/guides"
weight = 2

# izbornik podnožja
[[footer]]
name = "Suradnici"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Uvjeti"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Pravila Privatnosti"
pageRef = "/privacy-policy"
weight = 3
