############# Navigare în română ##############

# meniul principal
[[main]]
name = "Țări"
weight = 1

[[main]]
parent = "Țări"
name = "România"
pageRef = "/guides/romania"
weight = 1

[[main]]
name = "Toate Ghidurile"
pageRef = "/guides"
weight = 2

# meniu subsol
[[footer]]
name = "Contribuitori"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Termeni"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Politica de Confidențialitate"
pageRef = "/privacy-policy"
weight = 3
