############# Česká navigace ##############

# hlavní menu
[[main]]
name = "Země"
weight = 1

[[main]]
parent = "Země"
name = "Všechny země"
pageRef = "/categories/"
weight = 0

[[main]]
parent = "Země"
name = "Česká republika"
pageRef = "/guides/czech-republic"
weight = 1

[[main]]
name = "Všechny Průvodce"
pageRef = "/guides"
weight = 2

# nabídka v patičce
[[footer]]
name = "Přispěvatelé"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Podmínky"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Zásady Ochrany Osobních Údajů"
pageRef = "/privacy-policy"
weight = 3
