############# Navigation en français ##############

# menu principal
[[main]]
name = "Pays"
weight = 1

[[main]]
parent = "Pays"
name = "France"
pageRef = "/categories/france"
weight = 1

[[main]]
name = "Tous les Guides"
pageRef = "/guides"
weight = 2

# menu pied de page
[[footer]]
name = "Contributeurs"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Conditions"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Politique de Confidentialité"
pageRef = "/privacy-policy"
weight = 3
