############# English navigation ##############

# main menu
[[main]]
name = "Countries"
weight = 1

[[main]]
parent = "Countries"
name = "Spain"
pageRef = "/categories/spain"

[[main]]
name = "All Guides"
pageRef = "/blog"
weight = 2

# footer menu
[[footer]]
name = "Contributors"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Terms & Conditions"
pageRef = "/terms"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
