############# Slovenská navigácia ##############

# hlavné menu
[[main]]
name = "Krajiny"
weight = 1

[[main]]
parent = "Krajiny"
name = "Slovensko"
pageRef = "/categories/slovakia"
weight = 1

[[main]]
name = "Všetky Sprievodcovia"
pageRef = "/guides"
weight = 2

# ponuka päty
[[footer]]
name = "Prispievatelia"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Podmienky"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Zásady Ochrany Osobných Údajov"
pageRef = "/privacy-policy"
weight = 3
