############# Nederlandse navigatie ##############

# hoofdmenu
[[main]]
name = "Landen"
weight = 1

[[main]]
parent = "Landen"
name = "Alle landen"
pageRef = "/categories/"
weight = 0

[[main]]
parent = "Landen"
name = "België"
pageRef = "/categories/belgium"
weight = 1

[[main]]
parent = "Landen"
name = "Nederland"
pageRef = "/categories/netherlands"
weight = 2

[[main]]
name = "Alle Gidsen"
pageRef = "/guides"
weight = 2

# voettekst menu
[[footer]]
name = "Bijdragers"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Voorwaarden"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Privacybeleid"
pageRef = "/privacy-policy"
weight = 3
