############# Deutsche Navigation ##############

# Hauptmenü
[[main]]
name = "Länder"
weight = 1

[[main]]
parent = "Länder"
name = "Alle Länder"
pageRef = "/categories/"
weight = 0

[[main]]
parent = "Länder"
name = "Deutschland"
pageRef = "/categories/germany"
weight = 1

[[main]]
parent = "Länder"
name = "Niederlande"
pageRef = "/categories/netherlands"
weight = 2

[[main]]
parent = "Länder"
name = "Österreich"
pageRef = "/categories/austria"
weight = 3

[[main]]
name = "Alle Anleitungen"
pageRef = "/guides"
weight = 2

# Fußmenü
[[footer]]
name = "Mitwirkende"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Bedingungen"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Datenschutzrichtlinie"
pageRef = "/privacy-policy"
weight = 3
