############# English navigation ##############

# main menu
[[main]]
name = "Countries"
weight = 1

[[main]]
parent = "Countries"
name = "Austria"
pageRef = "/guides/austria"
weight = 1

[[main]]
parent = "Countries"
name = "Belgium"
pageRef = "/guides/belgium"
weight = 2

[[main]]
parent = "Countries"
name = "Bulgaria"
pageRef = "/guides/bulgaria"
weight = 3

[[main]]
parent = "Countries"
name = "Croatia"
pageRef = "/guides/croatia"
weight = 4

[[main]]
parent = "Countries"
name = "Czech Republic"
pageRef = "/guides/czech-republic"
weight = 5

[[main]]
parent = "Countries"
name = "France"
pageRef = "/guides/france"
weight = 6

[[main]]
parent = "Countries"
name = "Germany"
pageRef = "/guides/germany"
weight = 7

[[main]]
parent = "Countries"
name = "Greece"
pageRef = "/guides/greece"
weight = 8

[[main]]
parent = "Countries"
name = "Hungary"
pageRef = "/guides/hungary"
weight = 9

[[main]]
parent = "Countries"
name = "Italy"
pageRef = "/guides/italy"
weight = 10

[[main]]
parent = "Countries"
name = "Poland"
pageRef = "/guides/poland"
weight = 11

[[main]]
parent = "Countries"
name = "Portugal"
pageRef = "/guides/portugal"
weight = 12

[[main]]
parent = "Countries"
name = "Romania"
pageRef = "/guides/romania"
weight = 13

[[main]]
parent = "Countries"
name = "Slovakia"
pageRef = "/guides/slovakia"
weight = 14

[[main]]
parent = "Countries"
name = "Spain"
pageRef = "/guides/spain"
weight = 15

[[main]]
parent = "Countries"
name = "Switzerland"
pageRef = "/guides/switzerland"
weight = 16

[[main]]
name = "All Guides"
pageRef = "/guides"
weight = 2

# footer menu
[[footer]]
name = "Contributors"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Terms"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3