############# Polska nawigacja ##############

# główne menu
[[main]]
name = "Kraje"
weight = 1

[[main]]
parent = "Kraje"
name = "Austria"
pageRef = "/categories/austria"
weight = 1

[[main]]
parent = "Kraje"
name = "Belgia"
pageRef = "/categories/belgium"
weight = 2

[[main]]
parent = "Kraje"
name = "Bułgaria"
pageRef = "/categories/bulgaria"
weight = 3

[[main]]
parent = "Kraje"
name = "Chorwacja"
pageRef = "/categories/croatia"
weight = 4

[[main]]
parent = "Kraje"
name = "Czechy"
pageRef = "/categories/czech-republic"
weight = 5

[[main]]
parent = "Kraje"
name = "Francja"
pageRef = "/categories/france"
weight = 6

[[main]]
parent = "Kraje"
name = "Niemcy"
pageRef = "/categories/germany"
weight = 7

[[main]]
parent = "Kraje"
name = "Grecja"
pageRef = "/categories/greece"
weight = 8

[[main]]
parent = "Kraje"
name = "Węgry"
pageRef = "/categories/hungary"
weight = 9

[[main]]
parent = "Kraje"
name = "Włochy"
pageRef = "/categories/italy"
weight = 10

[[main]]
parent = "Kraje"
name = "Polska"
pageRef = "/categories/poland"
weight = 11

[[main]]
parent = "Kraje"
name = "Portugalia"
pageRef = "/categories/portugal"
weight = 12

[[main]]
parent = "Kraje"
name = "Rumunia"
pageRef = "/categories/romania"
weight = 13

[[main]]
parent = "Kraje"
name = "Słowacja"
pageRef = "/categories/slovakia"
weight = 14

[[main]]
parent = "Kraje"
name = "Hiszpania"
pageRef = "/categories/spain"
weight = 15

[[main]]
parent = "Kraje"
name = "Szwajcaria"
pageRef = "/categories/switzerland"
weight = 16

[[main]]
name = "Wszystkie Przewodniki"
pageRef = "/guides"
weight = 2

# menu stopki
[[footer]]
name = "Współtwórcy"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Warunki"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Polityka Prywatności"
pageRef = "/privacy-policy"
weight = 3
