############# Navigazione in italiano ##############

# menu principale
[[main]]
name = "Paesi"
weight = 1

[[main]]
parent = "Paesi"
name = "Italia"
pageRef = "/guides/italy"
weight = 1

[[main]]
name = "Tutte le Guide"
pageRef = "/guides"
weight = 2

# menu piè di pagina
[[footer]]
name = "Collaboratori"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Termini"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Informativa sulla Privacy"
pageRef = "/privacy-policy"
weight = 3
