############# Deutsche Navigation ##############

# Hauptmenü
[[main]]
name = "Länder"
weight = 1

[[main]]
parent = "Länder"
name = "Deutschland"
pageRef = "/guides/germany"
weight = 1

[[main]]
name = "Alle Anleitungen"
pageRef = "/guides"
weight = 2

# Fußmenü
[[footer]]
name = "Mitwirkende"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Bedingungen"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Datenschutzrichtlinie"
pageRef = "/privacy-policy"
weight = 3
