############# Polska nawigacja ##############

# główne menu
[[main]]
name = "Kraje"
weight = 1

[[main]]
parent = "Kraje"
name = "Wszystkie kraje"
pageRef = "/categories/"
weight = 0

[[main]]
parent = "Kraje"
name = "Polska"
pageRef = "/categories/poland"
weight = 1

[[main]]
name = "Wszystkie Przewodniki"
pageRef = "/guides"
weight = 2

# menu stopki
[[footer]]
name = "Współtwórcy"
pageRef = "/authors"
weight = 1

[[footer]]
name = "Warunki"
pageRef = "/terms-and-conditions"
weight = 2

[[footer]]
name = "Polityka Prywatności"
pageRef = "/privacy-policy"
weight = 3
